### ISSUE TITLE
how to configure the resolution

### ISSUE THREAD

**Issue by alavaelian** [worron/awesome-config#63]
it seems that my monitor resolution is lower that the config is intended for, the background widget get mesed up  how i can configure it for lower resolution?.
My current resolution is 1600x900

**Comment by worron** [comment]
Widgets size can be configured thought theme files. Adapting to other resolution meant you have to reconfigure most of the widgets one by one. Plenty of work, but it's the only way, unfortunately.

**Comment by alavaelian** [comment]
thanks for the answer man , but how these files are called and where is the part to configure the size, and how I can determine the correct size of the widgets for my resolution, I am willing to do it because this config is neat

**Comment by worron** [comment]
[Theme files](https://github.com/worron/awesome-config/tree/master/themes) are part of config. You can check `rc` files to investigate which theme they associated, or simply try to assume by names. For example, if `ruby` config used, its theme file will be [ruby/theme.lua](https://github.com/worron/awesome-config/blob/master/themes/ruby/theme.lua). Also keep in mind that theme [can be based on another one](https://github.com/worron/awesome-config/blob/a38137620f769089cc4786b6cf2c241b085ea1dc/themes/ruby/theme.lua#L6-L8). So in this example, `ruby` config depend on whole chain of theme files `ruby/theme.lua` → `colored/theme.lua` → `colorless/theme.lua`.

Theme files have some tip commentaries which part certain settings belong, for more detail you have to dig into widgets source code. Just try to experiment with numbers and check how it fit your screen. Desktop widgets are a bit tricky, you can set up [desktop](https://github.com/worron/awesome-config/blob/a38137620f769089cc4786b6cf2c241b085ea1dc/themes/ruby/theme.lua#L37-L41) grid (lines height, columns width, edges gap) for them rather than individual widget size. And adapt widget inner elements sizes after that.

**Comment by alavaelian** [comment]
thanks for the answer man i will try that
